name: bloc_riverpod_clean_arch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #? Dependency Injection
  injectable: ^1.5.3
  get_it: ^7.2.0


  #? State Management
  flutter_bloc: ^8.0.1            
  flutter_hooks: ^0.18.3          

  #? Network
  dio: ^4.0.6
  data_connection_checker_tv: ^0.3.5-nullsafety 

  #? Interface Utils
  google_fonts: ^2.3.2

  #? Dev Utils
  dartz: ^0.10.1                  
  equatable: ^2.0.3               
  flutter_screenutil: ^5.5.3+2
  freezed_annotation: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7            
  injectable_generator: ^1.5.2    
  freezed: ^2.0.3               

flutter:
  uses-material-design: true
